### ISSUE TITLE
Content

### ISSUE THREAD

**Issue by troettge** [learnB4SS/learnB4SS#1]
[Link to new document](https://docs.google.com/document/d/1SWO9WglDcKdNF3XmFWlsAx6lgrXUk5a4pRnwtIp5ja4/edit).

--------------------

Structure of Timo's Bayesian Workshop:

- Show them how easy brms works (live coding TIMO)
- Replication Crisis --> partly due to NHST, we need to rethink statistical inference (TIMO)
- Bayes theorem (vampire example) (TIMO)
     - Introduces concepts of prior and belief update.

- Application to Regression (JOSEPH)
  - Introduction to **data set**, introduction to research question (hypothesis) (JOSEPH)
  - HANDS-ON early on.

- inference over posterior (STEFANO)
  - ❓ Also introduce random variables?
  - ❓ Maybe little exercise or show them (conceptually) how you can get things from posteriors distrs.
  - Short exercise to do before the reconvening day on wrangling posteriors.
- NHST vs. Bayesian inference (JOSEPH)
   - ❓ Also introduce random variables?
- Pros and Con's of Bayesian inference (JOSEPH)
  - @stefanocoretta include pro's con's
- ~~"One more thing" running Baysian models is easy! Steve Jobs.~~

This part is related to R syntax.

- Introduction to **data set**, introduction to research question (hypothesis) (JOSEPH)
- explain brm() syntax, explain outcome (JOSEPH)
- **Interpret output** (JOSEPH)
  - interpret outcome, regression coefficients
  - HANDS-ON: RUN MODEL AND INTERPRET OUTPUT, EXTRACT POSTERIORS, PLOT
    - Save model output and ask for interpretations questions.
    - "You are fully operational now!"
- **Hypotheses** (TIMO)
  - testing hypothesis, parameter estimation, BF, LOO(?)
  - HANDS-ON: HYPOTHESIS() FUNCTION, parameter estimation 
- **Priors** (STEFANO)
  - Priors, types of priors, impact on posterior, syntax
    - "Priors are the boogie man"
  - Prior predictive checks?
  - HANDS-ON: SPECIFY PRIORS 
- **Diagnostics**, model convergence, and posterior predictive check (STEFANO)
  - Approximating probability distributions (island hopping example) (STEFANO)
  - HANDS-ON: Posterior predictive check
- Show reel, what you can do with it

**Comment by jvcasillas** [comment]
JVC: Some thoughts (mainly so I don't forget)

- Need to determine which aspects of "Practical part" lend themselves to learnr exercises
- Probably could work well for syntax and interpretation questions (like a quiz)
- Better for actually running code, but might be an issue for fitting brms models and sampling posterior (in learnr)

**Comment by jvcasillas** [comment]
Ok here is another draft for how we can organize. I didn't include any names for who does what (on purpose), as we may want to rethink that as we continue fleshing out the content/order. Everything labelled "Application to regression" is a hands on activity; anything else is theory.


- Intro
  - Replication Crisis --> partly due to NHST, 
  - we need to rethink statistical inference 
- Application to Regression pt 1 - Initial demo
  - Introduction to **data set** via live coding
  - Simplified freq/bda comparison, focus on what you get with BDA (a posterior)
  - Leads into "how does it work?" (how do we get a posterior?)
- Bayes theorem - how does it work? (vampire example) 
  - Introduces concepts of prior and belief update.
  - Probability and quantifying uncertainty
- Application to regression pt 2 - Prior and Bayesian updating 
  - What is a prior in regression?
  - How do we pick priors?
    - prior predictive checks
    - simulation and plotting
  - Demonstrate Bayesian updating (density plots?, something like this: https://seeing-theory.brown.edu/bayesian-inference/index.html#section3)
  - Revisit data set 
    - estimate intercept with different priors
    - add predictor
- NHST vs. Bayesian inference
  - Pros and Con's of Bayesian inference

---

- Brief review
- Application to regression pt 3 - Inference over posterior I
  - Credible intervals
  - ROPEs
  - Probability of direction
  - Bayes factors
  - (focus on showing all the possibilities with BDA vs. a p-value in Freq.)
- Sampling from the posterior
  - light intro to MCMC
  - NUTS
- Application to regression pt 4 - Inference over posterior II
  - wrangling posteriors
  - testing hypotheses
- More on priors
  - types of priors
  - impact on posterior
  - syntax
- Application to regression pt 5 - Leveling up
  - Add more predictors
  - Add group level effects
  - Diagnostics
  - Plotting
- Wrapping up
  - NHST vs. Bayesian inference revisited
  - Resources
  - Getting help

**Comment by stefanocoretta** [comment]
Here's my take on a topic timeline (this includes only concepts + methods, which has to be interspersed with practicals; jotted down now in a single spurt, so didn't think it through yet and might change my mind).

1. Parameters and probabilities.
  - Transition in: We want to answer a question about the universe.
  - Main: Random events, random variables, parameters, probability distributions.
  - Transition out: We sample data to obtain a probability distribution of a parameter.
2. Bayesian update.
  - Transition in: Parameter as a continuous variable (= intercept only model, y ~ Normal(mu, sigma)).
  - Main: Observed data + prior beliefs = posterior distribution.
  - Transition out: Bayesian update in action.
3. Operationalise prior knowledge (priors).
  - Transition in: We want to be able to capitalise on prior knowledge.
  - Main: Priors, type of priors, priors for location and scale parameters.
  - Transition out: We want to know the (posterior) probability distribution of mean and sd from y ~ Normal(mu, sigma).
4. Stan + brms.
  - Transition in: Calculating probability is analytically challenging.
  - Main: Take many random samples to approximate the posterior (Monte Carlo). Intercept-only model fit with brm().
  - Main: Interpret output (summary() and plot()).
  - Transition out: This is nice, but we are not normally interested in just a mean.

------------

5. Statistical inference.
  - Transition in: Remember we had a question about the universe?
  - Main: Descriptive and inferential statistics, explanatory/confirmatory inference, Frequentist, repro/repl crises, Bayesian inference/Bayes Theorem.
  - Transition out: Reasons to adopt Bayesian.
6. Hypotheses and inference.
  - Transition in: I got my posterior, now what?
  - Main: Inference with posterior, ROPE, Bayes Factor.
  - Transition out: Ok, fine, but how can I make all this pretty?
7. Visualisation.
8. Diagnostics.
9. Where to next? (showcase of what else can be done with Bayesian Data Analysis and brms/Stan).

**Comment by troettge** [comment]
@stefanocoretta @jvcasillas thanks for your proposal. how to we proceed now technically? It's difficult to comment on these proposals using github (its also difficult to see what some of the things might mean). Having two proposal makes it difficult to focus the conversation. We need to get going, so ideally we have one draft on wednesday that just needs smoothing out. Any suggestions?

**Comment by stefanocoretta** [comment]
Rereading Joseph's plan is basically almost identical to mine so should be easy to move forward. Perhaps we can move Jo's plan to Gdocs and comment there. (Sent you an invitation to a learnB4SS folder on Gdrive).

**Comment by troettge** [comment]
I have created a gdoc in said folder and comment on Jo's approach right now.

**Comment by stefanocoretta** [comment]
(Link to document)[https://docs.google.com/document/d/1SWO9WglDcKdNF3XmFWlsAx6lgrXUk5a4pRnwtIp5ja4/edit].
