### ISSUE TITLE
Quick check at materials website

### ISSUE THREAD

**Issue by stefanocoretta** [learnB4SS/learnB4SS#74]
Can you guys have a quick final look at the materials website? https://learnb4ss.github.io/learnB4SS/index.html

I'm aiming at sending out an email this evening with link to it and instructions.

@troettge @jvcasillas

**Comment by jvcasillas** [comment]
Looks good. The mobile color scheme is perfect now. All the links work for me except those that go to Timo's slides (should this be going to OSF yet? Also, I wonder if the starter kit might confuse people. The "normal" instructions seem pretty straightforward (to me). How would one choose between that and using the starter kit? The purpose is only to aid installation, right? I might make that more clear so that no n00bs think they have to open the starter kit every time they want to do a bayesian analysis, or something silly like that.

**Comment by troettge** [comment]
Looks good. How about Boomer-T tries to set things up later as a guinea pig during our meeting? And see what issues might arise / what needs clarification?

**Comment by stefanocoretta** [comment]
Jo, that's a good point! Perhaps I can be clearer that the kit is for the workshop only and that advanced useRs can just install the package where/how the like

**Comment by stefanocoretta** [comment]
P.S. Timo's slides are on GitHub too, I suspect that they just take some time to load

**Comment by stefanocoretta** [comment]
Ah no... my fault. Wrong links...
